List items
estartando-devs/Escala-as-Mina pull request #12
Opened 2020-12-01 04:39 UTC by teddiur

Also started a Typography component

2020-12-01 21:01 UTC, Brenont commented on src/components/Typography/index.jsx
> +        font={font}
```suggestion
  const { type, children, ...restProps } = props;

  if (type === "span") {
    return (
      <Span
        {...restProps}
      >
        {children}
      </Span>
    );
  } else {
    return (
      <Paragraph
        {...restProps}
```

2020-12-01 21:04 UTC, Brenont commented on src/pages/index.jsx
> +import { ListItem } from "../components";
Você importou esse componente mas não está utilizando ainda. Isso causa uma warning e o deploy quebra caso tenha warnings

2020-12-01 21:11 UTC, Brenont requested changes

2020-12-01 21:11 UTC, Brenont commented on src/components/Typography/styledText.jsx
> +      -moz-text-fill-color: trasparent;
Essas linhas não são necessarias, o próprio React já trata o uso desses prefixos de compatibilidade :smiley:

2020-12-01 21:11 UTC, Brenont commented on src/components/Typography/index.jsx
> +    );
```suggestion
  const { type, children, ...restProps } = props;

  if (type === "span") {
    return <Span {...restProps}>{children}</Span>;
  } else {
    return <Paragraph {...restProps}>{children}</Paragraph>;
```

2020-12-01 21:22 UTC, Brenont reviewed
Muito bom Rodrigo!

2020-12-01 23:09 UTC, teddiur reviewed
Tirei o componente que não esta sendo usado

2020-12-02 00:19 UTC, teddiur reviewed
Alterei o text-fill-color

2020-12-02 00:24 UTC, rednerdoficial approved these changes

2020-12-02 00:24 UTC, rednerdoficial approved these changes

2020-12-02 00:27 UTC, rednerdoficial approved these changes

2020-12-02 00:27 UTC, rednerdoficial approved these changes

2020-12-02 14:49 UTC, teddiur reviewed
Sugestão de ...restProps incluída

2020-12-03 23:22 UTC, Brenont approved these changes
aulas e palestras

2020-12-03 23:22 UTC, merged